#!/bin/bash -x
#
# +--work/arc  --original packages
# +--conf  --this dir
# | \--conf/kernel  -- kernel archive
# |   \--conf/kernel/meson3  -- bsp
# |
# +--work 
# | \--work/srcs  -- source dir
# |    \--work/srcs/arm_ref/m1-kernel-android   -- kernel dir
# |

if [ ! -d kernel ] ; then mkdir kernel; fi

EXC='--exclude=*.o --exclude=*.o.cmd --exclude=*.builtin --exclude=*.order'

rsync -tv $1  $EXC ../work/srcs/xstamp0 . 
rsync -tv $1  $EXC ../work/srcs/arm_ref/m1-kernel-android/env.sh    kernel/
rsync -tv $1  $EXC ../work/srcs/arm_ref/m1-kernel-android/k1ocfg.sh kernel/
rsync -tv $1  $EXC ../work/srcs/arm_ref/m1-kernel-android/k2mcfg.sh kernel/
rsync -tv $1  $EXC ../work/srcs/arm_ref/m1-kernel-android/k3bld.sh  kernel/
rsync -tv $1  $EXC ../work/srcs/arm_ref/m1-kernel-android/k9clean.sh kernel/
rsync -rtv $1 $EXC ../work/srcs/arm_ref/m1-kernel-android/arch/arm/mach-meson3 kernel/

